<?php
$themelayout = "5"; //4, 5, tablet
$TZ = "Europe/London";
$theme = isset($theme) ? $theme : "dark";
$theme1 = $theme; 
$extralinks   = "yes";
$languages   = "yes";
$dateFormat   = "d-m-Y"; //m-d-Y, Y-m-d
$timeFormat    = "H:i:s"; //g:i:s, g:i:s a
$timeFormatShort    = "H:i"; //g:i, g:i a
$clockformat    = "24"; //12, 24
$advisoryzone = "uk"; //uk, na, eu, au, rw (= UK, North America, Europe, Australia, Rest of World)
$airqual["in_use"] = "yes"; // yes, no
$airqual["zone"] = "uk"; //uk, us, ei, ci, au, (= UK DAQI, US EPS, Europe EAQI, Europe CAQI, Australia)
$airqual["source"] = "weewx";  //purple, weewx, sds
$lightning["source"] = '0'; // use 'Boltek' or '0'
$position2   = "dvmAirqualityTop.php"; 
$position3   = "dvmLightningTop.php"; 
$position5   = "dvmTemperatureModule.php";
$position6   = "dvmForecastModule.php";
$position7   = "dvmCurrentModule.php";
$position8   = "dvmWindModule.php";
$position9   = "dvmRainfallModule.php";
$position10   = "dvmBarometerModule.php";
$position11   = "dvmIndoorTemperatureModule.php";
$position12   = "dvmSolarUvLuxModule.php";
$position13   = "dvmLightningModule.php";
$position14   = "dvmAirqualityModule.php";
$position15   = "dvmWebcamModule.php";
$position16   = "dvmEarthquakeModule.php";
$position17   = "dvmEarthDaylightModule.php";
$position18    = "dvmSolarDialModule.php";
$position19   = "dvmMoonPhaseModule.php";
$position20   = "";
$webcamurl   = "";
$videoWeatherCamURL  = "";
$email    = "";
$twitter   = "";
$since    = "2021";
$defaultlanguage   = "en";
$password    = "";
$flag   = "en";
$manifestShortName = "MYWX";
$notifications = "yes";
$notifyWind = "yes";
$notifyEarthquake = "yes";
$notifyMagnitude = 3;
$linkWU = "yes";
$linkWUNew = "yes";
$id = "IYOURWUKWY";
$linkCWOPID = "";
$linkFindUID = "";
$linkNOAA = "yes";
$linkMADIS = "yes";
$linkMesoWest = "yes";
$linkWeatherCloudID = "";
$linkWindyID = "";
$linkAWEKASID = "";
$linkAmbientWeatherID = "";
$linkPWSWeatherID = "";
$linkMetOfficeID = "";
$linkCustom1Title = "Services Config";
$linkCustom1URL = "https://steepleian.github.io/weewx-divumwx-divumwx/divumwx_settings_txt.html";
$linkCustom2Title = "";
$linkCustom2URL = "";
$USAWeatherFinder = "";
$extraLinkTitle = "";
$extraLinkColor = "";
$extraLinkURL = "";


?>
