<?php
$themelayout = "extra_row"; //extra_row, extra_col, extra_row_col, tablet
$TZ = "Europe/London";
$theme = isset($theme) ? $theme : "dark";
$theme1 = $theme; 
$units = "eu"; //us, uk, metric, ca, scandinavia
$extralinks   = "yes";
$languages   = "yes";
$dateFormat   = "d-m-Y"; //m-d-Y, Y-m-d
$timeFormat    = "H:i:s"; //g:i:s, g:i:s a
$timeFormatShort    = "H:i"; //g:i, g:i a
$clockformat    = "24"; //12, 24
$advisoryzone = "uk"; //uk, na, eu, au, rw (= UK, North America, Europe, Australia, Rest of World) 
$position2   = "dvmWindGustYearTop.php";
$position2title   = "Wind <ored> Month | Year"; 
$position3   = "dvmLightningEwTop.php";
$position3title   = "Lightning <ored> Strikes"; 
$position5   = "dvmTemperatureModule.php";
$position5title   = "Temperature"; 
$position6   = "dvmForecastModule.php";
$position6title   = "Forecast"; 
$position7   = "dvmCurrentModule.php";
$position7title   = "Current Conditions"; 
$position8   = "dvmWindModule.php";
$position8title   = "Wind Speed & Direction"; 
$position9   = "dvmBarometerModule.php";
$position9title   = "Barometer"; 
$position10   = "dvmSolarDialModule.php";
$position10title   = "Solar Dial"; 
$position11   = "dvmRainfallModule.php";
$position11title   = "Rainfall"; 
$position12   = "dvmSolarUvLuxModule.php";
$position12title   = "Solar | UV | Lux"; 
$position13   = "dvmMoonPhaseModule.php";
$position13title   = "Moonphase"; 
$position14   = "dvmEarthquakeModule.php";
$position14title   = "Earthquake"; 
$position15   = "dvmWebcamModule.php";
$position15title   = "Cloudcam"; 
$position16   = "dvmEarthDaylightModule.php";
$position16title   = "Earth Daylight | Darkness"; 
$position17   = "";
$position17title   = "";
$position18   = "";
$position18title   = ""; 
$position19   = "";
$position19title   = ""; 
$position120   = "";
$position120title   = "";
$webcamurl   = "";
$videoWeatherCamURL  = "";
$email    = "";
$twitter   = "";
$since    = "2021";
$defaultlanguage   = "en";
$password    = "";
$flag   = "en";
$manifestShortName = "MYWX";
$notifications = "yes";
$notifyWind = "yes";
$notifyEarthquake = "yes";
$notifyMagnitude = 3;
$linkWU = "yes";
$linkWUNew = "yes";
$id = "IYOURWUKWY";
$linkCWOPID = "";
$linkFindUID = "";
$linkNOAA = "yes";
$linkMADIS = "yes";
$linkMesoWest = "yes";
$linkWeatherCloudID = "";
$linkWindyID = "";
$linkAWEKASID = "";
$linkAmbientWeatherID = "";
$linkPWSWeatherID = "";
$linkMetOfficeID = "";
$linkCustom1Title = "Services Config";
$linkCustom1URL = "https://steepleian.github.io/weewx-Weather34/divumwx_settings_txt.html";
$linkCustom2Title = "";
$linkCustom2URL = "";
$USAWeatherFinder = "";
$extraLinkTitle = "";
$extraLinkColor = "";
$extraLinkURL = "";


?>
